// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: vehicle/vehicle.proto

package vehiclepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPosition) Reset() {
	*x = GetPosition{}
	mi := &file_vehicle_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPosition) ProtoMessage() {}

func (x *GetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPosition.ProtoReflect.Descriptor instead.
func (*GetPosition) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *GetPosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetPosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetPositionHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*GetPosition         `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionHistory) Reset() {
	*x = GetPositionHistory{}
	mi := &file_vehicle_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionHistory) ProtoMessage() {}

func (x *GetPositionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionHistory.ProtoReflect.Descriptor instead.
func (*GetPositionHistory) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *GetPositionHistory) GetPositions() []*GetPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type UpdatePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePosition) Reset() {
	*x = UpdatePosition{}
	mi := &file_vehicle_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePosition) ProtoMessage() {}

func (x *UpdatePosition) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePosition.ProtoReflect.Descriptor instead.
func (*UpdatePosition) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdatePosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PersistLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistLocation) Reset() {
	*x = PersistLocation{}
	mi := &file_vehicle_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistLocation) ProtoMessage() {}

func (x *PersistLocation) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistLocation.ProtoReflect.Descriptor instead.
func (*PersistLocation) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{3}
}

var File_vehicle_vehicle_proto protoreflect.FileDescriptor

var file_vehicle_vehicle_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x70, 0x62, 0x22, 0x47, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x4a, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x70, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x70, 0x62, 0x42, 0x0c, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x0b, 0x2e, 0x3b, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x56, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x70, 0x62, 0xca, 0x02, 0x09, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x70, 0x62, 0xe2, 0x02, 0x15, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x70, 0x62,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vehicle_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_vehicle_proto_rawDescData = file_vehicle_vehicle_proto_rawDesc
)

func file_vehicle_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(file_vehicle_vehicle_proto_rawDescData)
	})
	return file_vehicle_vehicle_proto_rawDescData
}

var file_vehicle_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vehicle_vehicle_proto_goTypes = []any{
	(*GetPosition)(nil),        // 0: vehiclepb.GetPosition
	(*GetPositionHistory)(nil), // 1: vehiclepb.GetPositionHistory
	(*UpdatePosition)(nil),     // 2: vehiclepb.UpdatePosition
	(*PersistLocation)(nil),    // 3: vehiclepb.PersistLocation
}
var file_vehicle_vehicle_proto_depIdxs = []int32{
	0, // 0: vehiclepb.GetPositionHistory.positions:type_name -> vehiclepb.GetPosition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vehicle_vehicle_proto_init() }
func file_vehicle_vehicle_proto_init() {
	if File_vehicle_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vehicle_vehicle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vehicle_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_vehicle_proto_depIdxs,
		MessageInfos:      file_vehicle_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_vehicle_proto = out.File
	file_vehicle_vehicle_proto_rawDesc = nil
	file_vehicle_vehicle_proto_goTypes = nil
	file_vehicle_vehicle_proto_depIdxs = nil
}
